### ISSUE TITLE
Warteschleife nach vorzeitiger Launcher Beendigung

### ISSUE THREAD

**Issue by PaxJaromeMalues** [SALS-App/SALS#1]
Ich hatte jetzt mehrfach das Problem, dass, wenn ich den Launcher schließe während ArmA3 noch läuft und den Launcher nach Beendigung von ArmA3 erneut starten möchte, dieser in eine nicht endende Wartschleife (dunkelblaues Feld "Bitte warten") fällt.

Dieses Verhalten überlebt sogar einen Reboot des Systems.

Einzige Lösung hierfür scheint das löschen des blauen Cache zu sein, woraufhin das Modpack zeitaufwendig neu überprüft werden muss.

**Comment by TAINCER** [comment]
Wenn das auftritt bitte einmal <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> drücken.

Dann sollte die Entwicklerkonsole aufkommen, wo du oben auf "Console" clicken kannst. Falls die Meldungen darin nicht gut leserlich sind, einfach in die Konsole reinclicken und einmal <kbd>F5</kbd> dürcken.

Hier sollte nun eine rote Meldung sein. Davon dann bitte einmal einen screenshot machen, oder die Meldung in Textform eisenden.

![image](https://user-images.githubusercontent.com/41272726/100387666-f4463900-3028-11eb-97cb-0d1b2bd03a44.png)

**Comment by TAINCER** [comment]
Das Problem scheint an einem korrupten Caches zu liegen. Dies wird in der Version 1.0.0 gefixt.

**Comment by PaxJaromeMalues** [comment]
Bei mir ist es bisher nicht mehr aufgetreten, allerdings weil ich es mir abgewöhnt habe den Launcher zu schließen.

**Comment by OneTwo9th** [comment]
Hier ist der Balken stehen gebieben ich gleube er hatte aber trotzdem alles geladen, sorry erst zu spät gesehen.

![1](https://user-images.githubusercontent.com/18664310/115113462-c4251580-9f8a-11eb-8b8d-b7acfff894ab.JPG)

> Config Integrity check done.
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 downloadPath - 11
main.00142604acb2472ddb0e.js:1 Object
main.00142604acb2472ddb0e.js:1 Mode electron
main.00142604acb2472ddb0e.js:1 Electron ipcRenderer EventEmitter
main.00142604acb2472ddb0e.js:1 NodeJS childProcess Object
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.
e.warn @ main.00142604acb2472ddb0e.js:1
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 Object
main.00142604acb2472ddb0e.js:1 2
main.00142604acb2472ddb0e.js:1 autoStartArma - 7
main.00142604acb2472ddb0e.js:1 Object__proto__: Object
(anonymous) @ main.00142604acb2472ddb0e.js:1
main.00142604acb2472ddb0e.js:1 ----LF--
main.00142604acb2472ddb0e.js:1 Object
main.00142604acb2472ddb0e.js:1 object
main.00142604acb2472ddb0e.js:1 ----/LF--
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 Started Deletion
main.00142604acb2472ddb0e.js:1 Deletion Done
main.00142604acb2472ddb0e.js:1 Downloading Started
main.00142604acb2472ddb0e.js:1 Downloading: 2\@Jbad\Addons\anrop_jbad_legacy_compat_main.pbo, raw: @Jbad\Addons\anrop_jbad_legacy_compat_main.pbo from https://s3-1.sals.app/rosenrudel-standard/%40Jbad/Addons/anrop_jbad_legacy_compat_main.pbo
main.00142604acb2472ddb0e.js:1 Done
main.00142604acb2472ddb0e.js:1 Caching: 2\@Jbad\Addons\anrop_jbad_legacy_compat_main.pbo
main.00142604acb2472ddb0e.js:1 Done
main.00142604acb2472ddb0e.js:1 Downloading: 2\@Jbad\Addons\anrop_jbad_legacy_compat_main.pbo.anrop_jbad_legacy_compat-1.1.3.bisign, raw: @Jbad\Addons\anrop_jbad_legacy_compat_main.pbo.anrop_jbad_legacy_compat-1.1.3.bisign from https://s3-1.sals.app/rosenrudel-standard/%40Jbad/Addons/anrop_jbad_legacy_compat_main.pbo.anrop_jbad_legacy_compat-1.1.3.bisign
main.00142604acb2472ddb0e.js:1 Done
main.00142604acb2472ddb0e.js:1 Caching: 2\@Jbad\Addons\anrop_jbad_legacy_compat_main.pbo.anrop_jbad_legacy_compat-1.1.3.bisign
main.00142604acb2472ddb0e.js:1 Done
main.00142604acb2472ddb0e.js:1 Downloading Done
main.00142604acb2472ddb0e.js:1 autoStartArma - 7sn

Nach dem F5 drücken

> Config Integrity check done.
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 downloadPath - 11
main.00142604acb2472ddb0e.js:1 {production: true, environment: "PROD", chuckSize: 10, name: "rosenrudel", fileKey: "RR", …}
main.00142604acb2472ddb0e.js:1 Mode electron
main.00142604acb2472ddb0e.js:1 Electron ipcRenderer EventEmitter {_events: {…}, _eventsCount: 0, _maxListeners: undefined, send: ƒ, sendSync: ƒ, …}
main.00142604acb2472ddb0e.js:1 NodeJS childProcess {_forkChild: ƒ, ChildProcess: ƒ, exec: ƒ, execFile: ƒ, execFileSync: ƒ, …}
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.
e.warn @ main.00142604acb2472ddb0e.js:1
t.supports @ main.00142604acb2472ddb0e.js:1
e._findPluginFor @ main.00142604acb2472ddb0e.js:1
e.addEventListener @ main.00142604acb2472ddb0e.js:1
e.listen @ main.00142604acb2472ddb0e.js:1
e.listen @ main.00142604acb2472ddb0e.js:1
Ko @ main.00142604acb2472ddb0e.js:1
da @ main.00142604acb2472ddb0e.js:1
ja @ main.00142604acb2472ddb0e.js:1
ka @ main.00142604acb2472ddb0e.js:1
da @ main.00142604acb2472ddb0e.js:1
ja @ main.00142604acb2472ddb0e.js:1
ka @ main.00142604acb2472ddb0e.js:1
da @ main.00142604acb2472ddb0e.js:1
ca @ main.00142604acb2472ddb0e.js:1
Pa @ main.00142604acb2472ddb0e.js:1
t.create @ main.00142604acb2472ddb0e.js:1
t.create @ main.00142604acb2472ddb0e.js:1
e.createComponent @ main.00142604acb2472ddb0e.js:1
e.activateWith @ main.00142604acb2472ddb0e.js:1
e.activateRoutes @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e.activateChildRoutes @ main.00142604acb2472ddb0e.js:1
e.activate @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._tryNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._tryNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
t._complete @ main.00142604acb2472ddb0e.js:1
t.complete @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._tryNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t.notifyNext @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
t._next @ main.00142604acb2472ddb0e.js:1
t.next @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e._trySubscribe @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
e.call @ main.00142604acb2472ddb0e.js:1
e.subscribe @ main.00142604acb2472ddb0e.js:1
z @ main.00142604acb2472ddb0e.js:1
t._innerSub @ main.00142604acb2472ddb0e.js:1
t._tryNext @ main.00142604acb2472ddb0e.js:1
Promise.then (async)
v @ polyfills.00e0ac70c7a61a994d40.js:1
e.scheduleTask @ polyfills.00e0ac70c7a61a994d40.js:1
onScheduleTask @ polyfills.00e0ac70c7a61a994d40.js:1
e.scheduleTask @ polyfills.00e0ac70c7a61a994d40.js:1
t.scheduleTask @ polyfills.00e0ac70c7a61a994d40.js:1
t.scheduleMicroTask @ polyfills.00e0ac70c7a61a994d40.js:1
I @ polyfills.00e0ac70c7a61a994d40.js:1
e.then @ polyfills.00e0ac70c7a61a994d40.js:1
e.appInitializer @ main.00142604acb2472ddb0e.js:1
e.runInitializers @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
e.invoke @ polyfills.00e0ac70c7a61a994d40.js:1
onInvoke @ main.00142604acb2472ddb0e.js:1
e.invoke @ polyfills.00e0ac70c7a61a994d40.js:1
t.run @ polyfills.00e0ac70c7a61a994d40.js:1
e.run @ main.00142604acb2472ddb0e.js:1
e.bootstrapModuleFactory @ main.00142604acb2472ddb0e.js:1
zUnb @ main.00142604acb2472ddb0e.js:1
l @ runtime.69aad174de386c36a16c.js:1
0 @ main.00142604acb2472ddb0e.js:1
l @ runtime.69aad174de386c36a16c.js:1
t @ runtime.69aad174de386c36a16c.js:1
r @ runtime.69aad174de386c36a16c.js:1
(anonymous) @ main.00142604acb2472ddb0e.js:1
Show 170 more frames
main.00142604acb2472ddb0e.js:1 repoId - 12
main.00142604acb2472ddb0e.js:1 {}
main.00142604acb2472ddb0e.js:1 0
main.00142604acb2472ddb0e.js:1 autoStartArma - 7

**Comment by TAINCER** [comment]
Fixed in 1.0
